# Generated by Django 5.0.3 on 2024-04-16 18:20

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("svsaweb", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="boundary",
            name="boundary",
        ),
        migrations.RemoveField(
            model_name="boundary",
            name="name",
        ),
        migrations.AddField(
            model_name="boundary",
            name="area_km2",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="boundary",
            name="cd_mun",
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AddField(
            model_name="boundary",
            name="geom",
            field=django.contrib.gis.db.models.fields.PolygonField(
                null=True, srid=4674
            ),
        ),
        migrations.AddField(
            model_name="boundary",
            name="nm_mun",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="boundary",
            name="sigla_uf",
            field=models.CharField(max_length=2, null=True),
        ),
    ]
