# Generated by Django 5.0.3 on 2024-04-16 18:55

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("svsaweb", "0002_remove_boundary_boundary_remove_boundary_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="maplocation",
            name="boundary",
        ),
        migrations.RemoveField(
            model_name="maplocation",
            name="description",
        ),
        migrations.RemoveField(
            model_name="maplocation",
            name="name",
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("cd_mun", models.CharField(max_length=7)),
                ("nm_mun", models.CharField(max_length=50)),
                ("sigla_uf", models.CharField(max_length=2)),
                ("area_km2", models.FloatField()),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
                (
                    "location",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="svsaweb.maplocation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Neighborhood",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        null=True, srid=4326
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="svsaweb.city"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Boundary",
        ),
    ]
